# the base URL of your notes Github pages website
base_url: https://gyula-ny.github.io/n/

# the URL of your notes Github repo
repo_url: https://github.com/gyula-ny/n

# the name for your notes website
name: Notes(z)

# the description of the notes website
description: minimally personal notes of my self

