# the base URL of your notes Github pages website
base_url: https://abhin4v.github.io/precis

# the URL of your notes Github repo
repo_url: https://github.com/abhin4v/precis

# the name for your notes website
name: Precis

# the description of the notes website
description: Precis is a minimal note taking web-app built over Github Pages. This website itself is built using Precis. Look at the notes below to learn about it.